# Generated by Django 4.2.3 on 2024-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('weaver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('society_name', models.CharField(max_length=255)),
                ('master_weaver_name', models.CharField(max_length=255)),
                ('weaver_code', models.CharField(max_length=255)),
                ('weaver_card', models.CharField(blank=True, max_length=255, null=True)),
                ('ration_card', models.CharField(blank=True, max_length=255, null=True)),
                ('nhdc_passbook', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_card', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('door_no', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mandal', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_charkas', models.IntegerField(blank=True, null=True)),
                ('no_of_looms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
