# Generated by Django 4.2.3 on 2024-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWeaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_weaver_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('door_no', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mandal', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
